[package]
name = "jrsonnet-evaluator"
description = "jsonnet interpreter"
version = "0.3.2"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serialized-stdlib", "faster", "explaining-traces", "serde-json"]
# Serializes standard library AST instead of parsing them every run
serialized-stdlib = ["serde", "bincode", "jrsonnet-parser/deserialize"]
# Allow to convert Val into serde_json::Value and backwards
serde-json = ["serde", "serde_json"]
# Same as above, but with generated code instead of serde. Reduces memory usage, but increases binary size and compilation time
codegenerated-stdlib = []
# Replace some standard library functions with faster implementations (I.e manifestJsonEx)
# Library works fine without this feature, but requires more memory and time for std function calls
faster = []
# Rustc-like trace visualization
explaining-traces = ["annotate-snippets"]

# Unlocks extra features, but works only on unstable
unstable = []

[dependencies]
jrsonnet-parser = { path = "../jrsonnet-parser", version = "0.3.2" }
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.3.2" }
jrsonnet-types = { path = "../jrsonnet-types", version = "0.3.2" }
pathdiff = "0.2.0"

closure = "0.3.0"
indexmap = "1.6.0"

md5 = "0.7.0"
base64 = "0.13.0"
rustc-hash = "1.1.0"

thiserror = "1.0.22"

# Serialized stdlib
[dependencies.serde]
version = "1.0.117"
optional = true
[dependencies.bincode]
version = "1.3.1"
optional = true

# Serde json
[dependencies.serde_json]
version = "1.0.59"
optional = true

# Explaining traces
[dependencies.annotate-snippets]
version = "0.9.0"
features = ["color"]
optional = true

[build-dependencies]
jrsonnet-parser = { path = "../jrsonnet-parser", features = ["dump", "serialize", "deserialize"], version = "0.3.0" }
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.3.0" }
structdump = "0.1.2"
serde = "1.0.117"
bincode = "1.3.1"
